# Spotify Streaming Audit, Hackathon - Grupo #3

## Exploring Data Analisys

In [1]:
# Cargamos las librerías necesarias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Importamos los datasets y creamos los dataframes

In [6]:
# Cargamos los datos de Spotify desde el archivo CSV
raw_spotify_data = pd.read_csv('../data/raw/Spotify-2000.csv')

# Cargamos los datos de los Grammy Awards desde el archivo CSV
raw_grammy_data = pd.read_csv('../data/raw/the_grammy_awards.csv')

# Revisamos el tamaño de los datasets
print(f"Spotify Data Shape: {raw_spotify_data.shape}")
print(f"Grammy Data Shape: {raw_grammy_data.shape}")

Spotify Data Shape: (1994, 15)
Grammy Data Shape: (4810, 10)

Visualizamos el contenido de ambos dataframes

### Spotify dataframe

In [23]:
# Visualizamos la información general del dataframe de Spotify
raw_spotify_data.info()
raw_spotify_data.head(10).T

<class 'pandas.DataFrame'>
RangeIndex: 1994 entries, 0 to 1993
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Index                   1994 non-null   int64
 1   Title                   1994 non-null   str
 2   Artist                  1994 non-null   str
 3   Top Genre               1994 non-null   str
 4   Year                    1994 non-null   int64
 5   Beats Per Minute (BPM)  1994 non-null   int64
 6   Energy                  1994 non-null   int64
 7   Danceability            1994 non-null   int64
 8   Loudness (dB)           1994 non-null   int64
 9   Liveness                1994 non-null   int64
 10  Valence                 1994 non-null   int64
 11  Length (Duration)       1994 non-null   str
 12  Acousticness            1994 non-null   int64
 13  Speechiness             1994 non-null   int64
 14  Popularity              1994 non-null   int64
dtypes: int64(11), str(4)
memory usage: 233.8 KB

,0,1,2,3,4,5,6,7,8,9
Index,1,2,3,4,5,6,7,8,9,10
Title,Sunrise,Black Night,Clint Eastwood,The Pretender,Waitin' On A Sunny Day,The Road Ahead (Miles Of The Unknown),She Will Be Loved,Knights of Cydonia,Mr. Brightside,Without Me
Artist,Norah Jones,Deep Purple,Gorillaz,Foo Fighters,Bruce Springsteen,City To City,Maroon 5,Muse,The Killers,Eminem
Top Genre,adult standards,album rock,alternative hip hop,alternative metal,classic rock,alternative pop rock,pop,modern rock,modern rock,detroit hip hop
Year,2004,2000,2001,2007,2002,2004,2002,2006,2004,2002
Beats Per Minute (BPM),157,135,168,173,106,99,102,137,148,112
Energy,30,79,69,96,82,46,71,96,92,67
Danceability,53,50,66,43,58,54,71,37,36,91
Loudness (dB),-14,-11,-9,-4,-5,-9,-6,-5,-4,-3
Liveness,11,17,7,3,10,14,13,12,10,24
Valence,68,81,52,37,87,14,54,21,23,66
Length (Duration),201,207,341,269,256,247,257,366,223,290
Acousticness,94,17,2,0,1,0,6,0,0,0
Speechiness,3,7,17,4,3,2,3,14,8,7
Popularity,71,39,69,76,59,45,74,69,77,82

Podemos notar de primera mano que el tipo de dato para la columna "Length (Duration)" no es el correcto (str), el cual debe ser corregido/cambiado a tipo 'int'

In [17]:
# Visualizamos la información estadística de las columnas numéricas del dataframe de Spotify
raw_spotify_data.describe()

,Index,Year,Beats Per Minute (BPM),Energy,Danceability,Loudness (dB),Liveness,Valence,Acousticness,Speechiness,Popularity
count,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.00000
mean,997.500000,1992.992979,120.215647,59.679539,53.238215,-9.008526,19.012036,49.408726,28.858074,4.994985,59.52658
std,575.762538,16.116048,28.028096,22.154322,15.351507,3.647876,16.727378,24.858212,29.011986,4.401566,14.35160
min,1.000000,1956.000000,37.000000,3.000000,10.000000,-27.000000,2.000000,3.000000,0.000000,2.000000,11.00000
25%,499.250000,1979.000000,99.000000,42.000000,43.000000,-11.000000,9.000000,29.000000,3.000000,3.000000,49.25000
50%,997.500000,1993.000000,119.000000,61.000000,53.000000,-8.000000,12.000000,47.000000,18.000000,4.000000,62.00000
75%,1495.750000,2007.000000,136.000000,78.000000,64.000000,-6.000000,23.000000,69.750000,50.000000,5.000000,71.00000
max,1994.000000,2019.000000,206.000000,100.000000,96.000000,-2.000000,99.000000,99.000000,99.000000,55.000000,100.00000

También podemos notar que la primer columna llamada 'Index' no aporta valor a la infromación, podría eliminarse más adelante.

### Grammy Awards dataframe

In [22]:
# Visualizamos las información general del dataframe de los Grammy Awards
raw_grammy_data.info()
raw_grammy_data.head()

<class 'pandas.DataFrame'>
RangeIndex: 4810 entries, 0 to 4809
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   year          4810 non-null   int64
 1   title         4810 non-null   str
 2   published_at  4810 non-null   str
 3   updated_at    4810 non-null   str
 4   category      4810 non-null   str
 5   nominee       4804 non-null   str
 6   artist        2970 non-null   str
 7   workers       2620 non-null   str
 8   img           3443 non-null   str
 9   winner        4810 non-null   bool
dtypes: bool(1), int64(1), str(8)
memory usage: 343.0 KB

,year,title,published_at,updated_at,category,nominee,artist,workers,img,winner
0,2019,62nd Annual GRAMMY Awards (2019),2020-05-19T05:10:28-07:00,2020-05-19T05:10:28-07:00,Record Of The Year,Bad Guy,Billie Eilish,"Finneas O'Connell, producer; Rob Kinelski & Fi...",https://www.grammy.com/sites/com/files/styles/...,True
1,2019,62nd Annual GRAMMY Awards (2019),2020-05-19T05:10:28-07:00,2020-05-19T05:10:28-07:00,Record Of The Year,"Hey, Ma",Bon Iver,"BJ Burton, Brad Cook, Chris Messina & Justin V...",https://www.grammy.com/sites/com/files/styles/...,True
2,2019,62nd Annual GRAMMY Awards (2019),2020-05-19T05:10:28-07:00,2020-05-19T05:10:28-07:00,Record Of The Year,7 rings,Ariana Grande,"Charles Anderson, Tommy Brown, Michael Foster ...",https://www.grammy.com/sites/com/files/styles/...,True
3,2019,62nd Annual GRAMMY Awards (2019),2020-05-19T05:10:28-07:00,2020-05-19T05:10:28-07:00,Record Of The Year,Hard Place,H.E.R.,"Rodney “Darkchild” Jerkins, producer; Joseph H...",https://www.grammy.com/sites/com/files/styles/...,True
4,2019,62nd Annual GRAMMY Awards (2019),2020-05-19T05:10:28-07:00,2020-05-19T05:10:28-07:00,Record Of The Year,Talk,Khalid,"Disclosure & Denis Kosiak, producers; Ingmar C...",https://www.grammy.com/sites/com/files/styles/...,True

Podemos notar que al igual, los tipos de datos para las columnas con fechas no son los correctos ('str'), deben ser corregitos a datatime.

In [26]:
# Visualizamos la información estadística de las columnas numéricas del dataframe de los Grammy Awards
raw_grammy_data.describe(include='all')

,year,title,published_at,updated_at,category,nominee,artist,workers,img,winner
count,4810.000000,4810,4810,4810,4810,4804,2970,2620,3443,4810
unique,NaN,62,4,10,638,4131,1658,2366,1463,1
top,NaN,62nd Annual GRAMMY Awards (2019),2017-11-28T00:03:45-08:00,2019-09-10T01:08:19-07:00,Song Of The Year,Steven Epstein,(Various Artists),"John Williams, composer (John Williams)",https://www.grammy.com/sites/com/files/styles/...,True
freq,NaN,433,4205,778,70,7,66,20,26,4810
mean,1995.566944,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,17.149720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1958.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1983.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1998.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2010.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2019.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

La información contenida en el segundo dataframe de los Grammy Awards, parece no ser tan relevante más que la columna 'winner' y porbablmente el 'year'.

## Datos únicos, nulos y/o duplicados

In [27]:
# Revisamos la cantidad de valores únicos en cada columna del dataframe de Spotify
raw_spotify_data.nunique()

Index                     1994
Title                     1958
Artist                     731
Top Genre                  149
Year                        63
Beats Per Minute (BPM)     145
Energy                      98
Danceability                84
Loudness (dB)               23
Liveness                    94
Valence                     97
Length (Duration)          350
Acousticness               100
Speechiness                 37
Popularity                  81
dtype: int64

In [28]:
# Revisamos la cantidad de valores únicos en cada columna del dataframe de Grammy Awards
raw_grammy_data.nunique()

year              62
title             62
published_at       4
updated_at        10
category         638
nominee         4131
artist          1658
workers         2366
img             1463
winner             1
dtype: int64